### ISSUE TITLE
Update link to "DG readiness tool" because of bad Microsoft maintenance

### ISSUE THREAD

**Issue by beerisgood** [savchenko/windows10#6]
Sadly their tool isn't up2date - even after 1,5 years reporting.
See https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5690#issuecomment-670680803

So until fixed better use https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool

**Comment by asvc** [comment]
Excellent point, I will update to the https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg-readiness-tool

Also, see the https://github.com/stoptracking/windows10/issues/5#issuecomment-671003165
